root: "/media/johann/data/imagenet"
num_classes: 1000
train_batch_size: 64
val_batch_size: 32
learning_rate: 0.256
momentum: 0.9
decay: 0.9
weight_decay: 0.00001
num_workers: 4 
epochs: 2
resume_from: ""
work_dir: ""
save_interval: 1
scheduler_step_size: 2
scheduler_gamma: 0.97